sudo: false
language: python

branches:
  except:
    - gh-pages

python:
  - 3.5

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
install:
  - conda create -q -n test python=3 pip numpy scipy pytest pandas astropy lxml html5lib
  - source activate test
  - pip install coveralls
  - pip install .
cache:
  directories:
    - miniconda

# command to run tests, e.g. python setup.py test
script:
  - py.test

after_success:
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: always
